import {cancelBestEffort,waitBounded} from './cleanup.mjs';
import {publicURL,publicAddress,admitAnswers,EGRESS_DISCLOSURE} from './public-reader.mjs';
export const DNS_ENDPOINT='https://cloudflare-dns.com/dns-query';
// Fixed free public DNS infrastructure. Fetch still resolves independently;
// none of these answers is a pinned connection destination.
export function createGuardedAdapter(fetchImpl=fetch){return {mode:EGRESS_DISCLOSURE.mode,async resolve(host,{signal,deadline,receipts=[],budget}){
 const normalized=host.replace(/^\[|\]$/g,'');if(publicAddress(normalized))return [normalized];
 const name=value=>{if(typeof value!=='string')throw Error('DNS_POLICY: malformed name');const h=new URL(publicURL('https://'+value.replace(/\.$/,'')+'/')).hostname;return h;};
 const start=name(host),pending=[{host:start,depth:0,path:[]}],resolved=new Set(),addresses=[],aliases=[];let queries=0;
 const guard=()=>{if(signal.aborted||Date.now()>=deadline)throw Error('DNS_DEADLINE: absolute budget exhausted');};
 const query=async(target,type)=>{guard();if(budget&&budget.dns_requests>=budget.max_dns_requests)throw Error('DNS_POLICY: aggregate query budget');if(++queries>10)throw Error('DNS_POLICY: query limit');if(budget)budget.dns_requests++;const q=new URL(DNS_ENDPOINT);q.searchParams.set('name',target);q.searchParams.set('type',type);let reader,response;const started=Date.now();try{response=await waitBounded(()=>fetchImpl(q.href,{method:'GET',redirect:'manual',credentials:'omit',headers:{accept:'application/dns-json'},signal}),{signal,deadline,error:()=>Error('DNS_DEADLINE: absolute budget exhausted'),onLate:r=>cancelBestEffort(r.body)});guard();if(response.status!==200)throw Error('DNS_HTTP '+response.status+'; terminal, not retried');reader=response.body?.getReader();if(!reader)throw Error('DNS_POLICY: empty DNS body');let bytes=0;const chunks=[];for(;;){guard();const r=await waitBounded(()=>reader.read(),{signal,deadline,error:()=>Error('DNS_DEADLINE: absolute budget exhausted')});guard();if(r.done)break;bytes+=r.value.length;if(budget){budget.bytes+=r.value.length;if(budget.bytes>budget.max_bytes)throw Error('AGGREGATE: DNS/body byte budget');}if(bytes>32768)throw Error('DNS_POLICY: response byte budget');chunks.push(r.value);}const raw=new Uint8Array(bytes);let off=0;for(const part of chunks){raw.set(part,off);off+=part.length;}const data=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(raw));if(data.Status!==0||data.TC===true||data.Answer!==undefined&&!Array.isArray(data.Answer)||data.Answer?.length>64)throw Error('DNS_POLICY: failed, truncated or excessive DNS answer');receipts.push({phase:'dns',dns_infrastructure:DNS_ENDPOINT,dns_name:target,dns_type:type,http_status:response.status,bytes,duration_ms:Date.now()-started,connection_pinned:false});return {type,records:data.Answer||[]};}finally{cancelBestEffort(reader||response?.body);}};
 while(pending.length){guard();const job=pending.shift();if(job.depth>4||job.path.includes(job.host))throw Error('DNS_POLICY: CNAME loop or chain budget');if(resolved.has(job.host))continue;resolved.add(job.host);const replies=await Promise.allSettled(['A','AAAA'].map(type=>query(job.host,type)));guard();const failed=replies.find(x=>x.status==='rejected');if(failed)throw failed.reason;let jobAddress=false,jobAliases=false;
 for(const reply of replies){const {type,records}=reply.value,edges=new Map(),ips=[];for(const record of records){const owner=name(record.name);if(typeof record.data!=='string')throw Error('DNS_POLICY: malformed record');if(record.type===1||record.type===28){if(!publicAddress(record.data))throw Error('DNS_POLICY: nonpublic or mixed address answer');ips.push({owner,address:record.data});}else if(record.type===5){const alias=name(record.data);if(edges.has(owner)&&edges.get(owner)!==alias)throw Error('DNS_POLICY: conflicting CNAME within one reply');edges.set(owner,alias);aliases.push(alias);if(aliases.length>16)throw Error('DNS_POLICY: CNAME count');}else throw Error('DNS_POLICY: unsupported answer record');}
 // A and AAAA replies may contain independently valid CDN chains. Validate
 // each complete chain, every record owner and every address; do not merge
 // incompatible per-query alias maps or ignore an unresolved alternate leaf.
 let leaf=job.host,depth=job.depth;const path=[...job.path];while(edges.has(leaf)){if(path.includes(leaf)||++depth>4)throw Error('DNS_POLICY: CNAME loop or chain budget');path.push(leaf);leaf=edges.get(leaf);}if(path.includes(leaf))throw Error('DNS_POLICY: CNAME loop');const reachable=new Set([...path,leaf]);for(const owner of edges.keys())if(!reachable.has(owner))throw Error('DNS_POLICY: unrelated CNAME record');for(const ip of ips){if(!reachable.has(ip.owner)||edges.has(ip.owner))throw Error('DNS_POLICY: address outside terminal chain');addresses.push(ip.address);jobAddress=true;if(addresses.length>64)throw Error('DNS_POLICY: address count');}
 receipts.push({phase:'dns_chain',dns_type:type,dns_name:job.host,cname_chain:path.slice(job.path.length),terminal_name:leaf,addresses:ips.map(x=>x.address),connection_pinned:false});
 if(edges.size){jobAliases=true;if(!ips.length){if(resolved.has(leaf))throw Error('DNS_POLICY: unresolved CNAME leaf loop');if(!pending.some(x=>x.host===leaf))pending.push({host:leaf,depth,path});}}
 }
 if(!jobAddress&&!jobAliases)throw Error('DNS_POLICY: unresolved answer');
 }
 const admitted=admitAnswers(addresses);receipts.push({phase:'dns_admission',dns_addresses_checked:[...admitted],cnames_checked:aliases,queries,...EGRESS_DISCLOSURE});return admitted;
 },guardedFetch(url,options){return fetchImpl(url,options);}};}
