// Bounded iterative structural writer, inspired by pinned moli-html2md.
import {parseHTML} from 'linkedom';
import {READER_LIMITS,publicURL} from './public-reader.mjs';
const longest=(text,ch)=>{let run=0,max=0;for(const c of text){run=c===ch?run+1:0;max=Math.max(max,run);}return max;};
const omit=new Set(['SCRIPT','STYLE','HEAD','NOSCRIPT','TEMPLATE','SVG']);
const esc=s=>s.replace(/[\\`*_\[\]<>#|]/g,'\\$&');
const destination=s=>s.replace(/[()<>\s]/g,c=>encodeURIComponent(c)).replace(/&/g,'&amp;');
export function structuralMarkdown(text,{url,type='text/html',deadline,signal,input_limit=READER_LIMITS.decoded_bytes}={}){let count=0,out='',truncated=false;const links=[];const guard=()=>{if(signal?.aborted||deadline&&Date.now()>=deadline)throw new Error('DEADLINE: extraction');};guard();if(new TextEncoder().encode(text).length>input_limit)throw new Error('Extraction input limit');if(type==='text/plain')return {title:'',markdown:esc(text).slice(0,READER_LIMITS.markdown_chars),truncated:esc(text).length>READER_LIMITS.markdown_chars,structure_loss:false,untrusted_source:true,links,full_browser:false};let markupNodes=0;const tags=/<[^>]*>/g;while(tags.exec(text)){guard();if(++markupNodes>READER_LIMITS.nodes)throw new Error('Extraction markup node budget exceeded before DOM allocation');}const {document}=parseHTML(text);guard();const title=(document.title||'').replace(/\s+/g,' ').trim().slice(0,512);const emit=s=>{const left=READER_LIMITS.markdown_chars-out.length;if(s.length>left)truncated=true;out+=s.slice(0,Math.max(0,left));};const boundary=()=>{if(out&&!out.endsWith('\n\n'))emit(out.endsWith('\n')?'\n':'\n\n');};
const stack=[{node:document.body||document,depth:0,quote:0,pre:false,list:[]}];let scripts=0;
while(stack.length){guard();const t=stack.pop();if(t.close!==undefined){emit(t.close);continue;}if(t.boundary){boundary();continue;}if(t.siblings){if(t.node){stack.push({...t,node:t.node.nextSibling});stack.push({...t,siblings:false});}continue;}if(++count>READER_LIMITS.nodes||t.depth>=READER_LIMITS.depth||out.length>=READER_LIMITS.markdown_chars){truncated=true;continue;}const n=t.node;if(n.nodeType===3){const s=t.pre?n.textContent:n.textContent.replace(/\s+/g,' ');emit(t.pre?s:esc(s));continue;}if(n.nodeType!==1&&n.nodeType!==9)continue;const tag=n.tagName||'';if(omit.has(tag)){if(tag==='SCRIPT')scripts++;continue;}if(n.hasAttribute?.('hidden')||n.getAttribute?.('aria-hidden')==='true')continue;let close='',quote=t.quote,pre=t.pre,list=t.list;if(/^H[1-6]$/.test(tag)){boundary();emit('#'.repeat(Number(tag[1]))+' ');stack.push({boundary:true});}else if(['P','DIV','SECTION','ARTICLE','MAIN','UL','OL','BLOCKQUOTE','PRE','TABLE'].includes(tag)){boundary();stack.push({boundary:true});}if(tag==='BR'){emit('\n'+' > '.repeat(quote));continue;}if(tag==='BLOCKQUOTE'){quote++;emit('> '.repeat(quote));}if(tag==='UL'||tag==='OL')list=[...list,{ordered:tag==='OL',next:Math.max(1,Math.min(9999,Number(n.getAttribute('start'))||1))}];if(tag==='LI'){if(out&&!out.endsWith('\n'))emit('\n');const l=list.at(-1);emit('  '.repeat(Math.max(0,list.length-1))+(l?.ordered?(l.next++)+'. ':'- '));close='\n';}if(tag==='STRONG'||tag==='B'){emit('**');close='**';}if(tag==='EM'||tag==='I'){emit('*');close='*';}if(tag==='A'&&links.length<32){try{const href=publicURL(new URL(n.getAttribute('href'),url).href);links.push({url:href,untrusted_source:true});emit('[');close=']('+destination(href)+')';}catch{}}if(tag==='CODE'&&!pre){const fence='`'.repeat(Math.min(1024,longest(n.textContent,'`')+1));emit(fence+' ');close=' '+fence;pre=true;}if(tag==='PRE'){const fence='~'.repeat(Math.min(1024,Math.max(3,longest(n.textContent,'~'))+1));emit(fence+'\n');close='\n'+fence+'\n';pre=true;}
// Simple direct-row tables use pipe rows; complex spans fall back to blocks.
if(tag==='TABLE'){let rows=[],valid=!['presentation','none'].includes((n.getAttribute('role')||'').toLowerCase());for(let r=n.firstElementChild;r;r=r.nextElementSibling){if(['THEAD','TBODY','TFOOT'].includes(r.tagName)){for(let row=r.firstElementChild;row;row=row.nextElementSibling)rows.push(row);}else if(r.tagName==='TR')rows.push(r);else valid=false;if(rows.length>100){valid=false;break;}}const grid=[];for(const row of rows){const cells=[];for(let cell=row.firstElementChild;cell;cell=cell.nextElementSibling){if(cells.length>=16||!['TH','TD'].includes(cell.tagName)||cell.hasAttribute('rowspan')&&cell.getAttribute('rowspan')!=='1'||cell.hasAttribute('colspan')&&cell.getAttribute('colspan')!=='1'||cell.querySelector('table,pre,ul,ol,h1,h2,h3,script,style')){valid=false;break;}cells.push(esc(cell.textContent.replace(/\s+/g,' ').trim()).slice(0,512));}grid.push(cells);}if(valid&&grid.length&&grid[0].length){const heading=rows[0].parentElement?.tagName==='THEAD'||Array.from(rows[0].children).every(c=>c.tagName==='TH');const width=Math.max(...grid.map(r=>r.length));if(grid.some(r=>r.length!==width))valid=false;if(valid){if(heading)emit('| '+grid.shift().join(' | ')+' |\n');else emit('| '+Array(width).fill('').join(' | ')+' |\n');emit('| '+Array(width).fill('---').join(' | ')+' |\n');for(const row of grid)emit('| '+row.join(' | ')+' |\n');continue;}}}
if(tag==='TD'||tag==='TH')close='\n\n';if(close)stack.push({close});if(n.firstChild)stack.push({node:n.firstChild,siblings:true,depth:t.depth+1,quote,pre,list});}
guard();return {title,markdown:out.trim(),links,truncated,structure_loss:true,visited_nodes:count,script_behavior:{executed:false,script_count:scripts},untrusted_source:true,full_browser:false,layout:false,screenshots:false,limitations:['Structural approximation: no CSS/layout or page script execution','Complex tables fall back to block text','Depth/node/output truncation reported']};}
