import {cancelBestEffort} from './cleanup.mjs';
import {accessSurface,remainingFreshness} from './response-quality.mjs';
import {allocateEvidence} from './batch-evidence.mjs';
import {createHttpGateway,HttpError} from './http-core.mjs';
import {publicURL,admitAnswers,EGRESS_DISCLOSURE} from './public-reader.mjs';
import {createGuardedAdapter} from './guarded-adapter.mjs';
import {acquireStatic} from './static-acquisition.mjs';
import {BUILD} from './config.mjs';
import {MERGE_LIMITS} from './merge-profile.mjs';
export {MERGE_LIMITS};
let isolateId;const isolateID=()=>isolateId??=crypto.randomUUID();
let active=0;const queue=[];const cache=new Map(),flights=new Map();let cacheBytes=0;
const typed=e=>({code:e.code||(/DEADLINE/.test(e.message)?'request_timeout':/AGGREGATE/.test(e.message)?'aggregate_limit':/HTTP (?:401|403|429)/.test(e.message)?'http_denial':/DNS_POLICY/.test(e.message)?'dns_policy':/URL_POLICY/.test(e.message)?'url_policy':/REDIRECT_POLICY/.test(e.message)?'redirect_policy':'acquisition_failed'),message:String(e.message||e).slice(0,300)});
export async function sharedRead(fn,signal){if(signal?.aborted)throw new HttpError('cancelled',499);await new Promise((resolve,reject)=>{const job={resolve:()=>{signal?.removeEventListener('abort',abort);active++;resolve();}};const abort=()=>{const i=queue.indexOf(job);if(i>=0)queue.splice(i,1);reject(new HttpError('cancelled',499));};signal?.addEventListener('abort',abort,{once:true});if(active<MERGE_LIMITS.active)job.resolve();else queue.push(job);});try{if(signal?.aborted)throw new HttpError('cancelled',499);return await fn();}finally{active--;queue.shift()?.resolve();}}
export function mergeState(){return {active,queued:queue.length,cache_entries:cache.size,cache_bytes:cacheBytes,isolate_id:isolateID(),cache_scope:'ephemeral per Worker isolate; durable cache pending',singleflight_methods:['GET','HEAD'],cached_methods:['GET'],...EGRESS_DISCLOSURE,arbitrary_public_read:true};}
const headersOf=h=>Object.fromEntries(['content-type','content-length','etag','last-modified','cache-control','content-language'].filter(k=>h.has(k)).map(k=>[k,h.get(k).slice(0,512)]));
export async function networkRequest(args,{signal,transport=createGuardedAdapter()}={}){const started=Date.now(),network=[],budget={requests:0,max_requests:5,dns_requests:0,max_dns_requests:40,bytes:0,max_bytes:1024*1024};let finalURL,sourceHeaders;
const gateway=createHttpGateway({methods:['GET','HEAD'],limits:{concurrency:MERGE_LIMITS.active,timeout:MERGE_LIMITS.item_ms,response:512*1024,aggregate:1024*1024,url:4096},authorize:async()=>true,policy:async p=>{publicURL(p.url);return {allowed:true,methods:['GET','HEAD'],headers:[]};},transport:async(p)=>{const coreSignal=p.signal;let url=publicURL(p.url);const seen=new Set();for(let hop=0;;hop++){if(coreSignal.aborted)throw new HttpError('cancelled',499);if(seen.has(url))throw new HttpError('redirect_loop');seen.add(url);const addresses=admitAnswers(await transport.resolve(new URL(url).hostname,{signal:coreSignal,deadline:started+MERGE_LIMITS.item_ms,receipts:network,budget}));budget.fetches=(budget.fetches||0)+1;const r=await transport.guardedFetch(url,{method:p.method,headers:{accept:'application/json, text/plain, text/html;q=0.8, */*;q=0.5'},credentials:'omit',redirect:'manual',signal:coreSignal});network.push({url,http_status:r.status,dns_addresses_checked:addresses});if([301,302,303,307,308].includes(r.status)){cancelBestEffort(r.body);if(hop>=4)throw new HttpError('redirect_limit');const location=r.headers.get('location');if(!location)throw new HttpError('redirect_location_missing');const next=publicURL(new URL(location,url).href);if(url.startsWith('https:')&&next.startsWith('http:'))throw new HttpError('https_downgrade');url=next;continue;}finalURL=url;sourceHeaders=r.headers;return r;}}});
const use=()=>({requests:budget.fetches||0,get_requests:(args.method||'GET')==='GET'?(budget.fetches||0):0,head_requests:args.method==='HEAD'?(budget.fetches||0):0,dns_requests:budget.dns_requests,decoded_bytes:budget.bytes});try{const r=await gateway.request({url:args.url,method:args.method||'GET',headers:{},body:new Uint8Array()}, {signal});const raw=r.body;const mime=(sourceHeaders.get('content-type')||'').split(';')[0].toLowerCase();let text,json;const textual=/^(text\/|application\/(?:json|[^;]+\+json))/.test(mime);if(textual&&raw?.length){text=new TextDecoder('utf-8',{fatal:true}).decode(raw);if(mime.includes('json'))try{json=JSON.parse(text);}catch{throw new HttpError('invalid_json');}}
const denied=[401,403,429].includes(r.status),httpFailure=r.status>=400;const surface=accessSurface({mime,text,json,headers:sourceHeaders}),challenge=surface.blocked===true;const semanticText=mime.includes('html')?(text||'').replace(/<(script|style|nav|header|footer)\b[^>]*>[\s\S]*?<\/\1>/gi,'').replace(/<[^>]*>/g,' ').trim():(text||'').trim();const jsonUseful=json===undefined||json!==null&&(typeof json!=='object'||Object.keys(json).length>0);const useful=!httpFailure&&!surface.partial&&(args.method==='HEAD'?r.status>=200&&r.status<400:raw?.length>0&&(!textual||semanticText.length>0&&jsonUseful)&&(!mime.includes('html')||semanticText.length>=40));const classification=challenge?(surface.classification||'challenge'):r.status===401?'auth_required':r.status===403?'access_denied':r.status===429?'rate_limit':r.status>=500?'upstream_failure':r.status===404?'not_found':httpFailure?'request_error':surface.partial?(surface.classification||'unconfirmed_response'):useful?'public_response':'empty';return {status:challenge||denied?'BLOCKED':httpFailure?'FAIL':useful?'PASS':'PARTIAL',retryable:!challenge&&[502,503,504].includes(r.status),automatic_retry:false,method:args.method||'GET',url:finalURL,http_status:r.status,headers:headersOf(sourceHeaders),decoded_bytes:r.metadata.bytes,sha256:r.metadata.sha256,hash_scope:'complete decoded response body',source_complete:true,...(textual?{text:text?.slice(0,6000)||'',text_truncated:(text?.length||0)>6000,...(json&&JSON.stringify(json).length<=6000?{json}: {})}:{binary:{mime,bytes:r.metadata.bytes,returned_bytes:false}}),resource_use:{...use(),decoded_bytes:r.metadata.bytes+budget.bytes},data_quality:{useful_data:!!useful&&!denied&&!challenge,classification_basis:surface.basis,classification,head_body_semantics:args.method==='HEAD'?'zero body; response headers only':undefined},network,retrievedAt:new Date().toISOString(),duration_ms:Date.now()-started,...EGRESS_DISCLOSURE,_cache_eligible:r.status===200&&!denied&&!challenge&&useful&&!sourceHeaders.has('set-cookie')&&!sourceHeaders.has('vary')&&!/private|no-store|no-cache/i.test(sourceHeaders.get('cache-control')||'')};}catch(e){return {status:'FAIL',method:args.method||'GET',url:args.url,error:typed(e),network,resource_use:use(),duration_ms:Date.now()-started,source_complete:false,hash_scope:null,...EGRESS_DISCLOSURE};}}
function eligible(out){return out.status==='PASS'&&!out.partial&&out.source_complete!==false&&out.static_provenance?.source_complete!==false&&out._cache_eligible===true;}
export function cacheTransport(base,meta){return {...base,resolve:base.resolve.bind(base),guardedFetch:async(...a)=>{const r=await base.guardedFetch(...a);const freshness=remainingFreshness(r.headers);meta.ttl=Math.min(meta.ttl??MERGE_LIMITS.cache_ttl_ms,freshness.ttl);meta.expires=Math.min(meta.expires??Infinity,Date.now()+freshness.ttl);if(!freshness.eligible||r.status!==200||r.headers.has('set-cookie')||r.headers.has('vary'))meta.eligible=false;return r;}};}
function prune(){const now=Date.now();for(const [k,v] of cache)if(now>=v.expires){cacheBytes-=v.bytes;cache.delete(k);}}
function networkCounts(out){const u=out.resource_use||{};return {get_requests:u.get_requests??(out.method==='HEAD'?0:u.requests||0),head_requests:u.head_requests??(out.method==='HEAD'?u.requests||0:0),dns_requests:u.dns_requests||0};}
function deliver(out,{started,fresh}){const value=structuredClone(out),counts=networkCounts(out);return {...value,source_network:counts,...(!fresh?{source_network_receipts:value.network||[]}:{ }),source_network_counts:counts,source_resource_use:value.resource_use||null,source_duration_ms:value.duration_ms??null,source_decoded_bytes:value.resource_use?.decoded_bytes??value.static_provenance?.source_decoded_bytes??value.decoded_bytes??0,fresh_decoded_bytes:fresh?(value.resource_use?.decoded_bytes??value.decoded_bytes??0):0,isolate_id:isolateID(),network:fresh?(value.network||[]):[],fresh_network:fresh?counts:{get_requests:0,head_requests:0,dns_requests:0},resource_use:fresh?value.resource_use:{requests:0,get_requests:0,head_requests:0,dns_requests:0,decoded_bytes:0},duration_ms:Date.now()-started};}
export async function mergedRead(kind,args,{signal,transport=createGuardedAdapter()}={}){const deliveryStarted=Date.now();if(signal?.aborted)throw new HttpError('cancelled',499);const url=publicURL(args.url),method=args.method||'GET',key=JSON.stringify([url,method,'public-read-v1',BUILD,kind,args.preset||'auto',args.verify_media||false,args.target_date||null,args.timezone||null,'server-default']);prune();const hit=method==='GET'&&cache.get(key);if(hit)return {...deliver(hit.value,{started:deliveryStarted,fresh:false}),cache:{hit:true,coalesced:false,fetchedAt:hit.fetchedAt,age_ms:Date.now()-hit.at,expiresAt:new Date(hit.expires).toISOString(),source_build:BUILD,scope:'ephemeral isolate',isolate_id:isolateID()}};
let flight=flights.get(key),coalesced=!!flight;if(!flight){const c=new AbortController(),timer=setTimeout(()=>c.abort('Item deadline exceeded'),MERGE_LIMITS.item_ms);flight={c,subscribers:0,cancelled:false};flight.promise=sharedRead(async()=>{const meta={eligible:true,ttl:MERGE_LIMITS.cache_ttl_ms};const out=kind==='network'?await networkRequest({...args,url},{signal:c.signal,transport:cacheTransport(transport,meta)}):await acquireStatic(url,{...args,signal:c.signal,transport:cacheTransport(transport,meta)});meta.ttl=Math.max(0,Math.min(meta.ttl, (meta.expires??(Date.now()+meta.ttl))-Date.now()));out._cache_eligible=out._cache_eligible!==false&&meta.eligible;flight.ttl=meta.ttl;const at=Date.now(),fetchedAt=out.retrievedAt||new Date(at).toISOString();out.retrievedAt=fetchedAt;const clean={...out,data_quality:out.data_quality||{useful_data:out.status==='PASS'&&out.content_acquired===true,classification:out.classification||'acquisition_failure'},...(out.status==='FAIL'&&typeof out.error==='string'?{error_detail:typed(new Error(out.error))}:{})};delete clean._cache_eligible;const bytes=new TextEncoder().encode(JSON.stringify(clean)).length;if(method==='GET'&&eligible(out)&&meta.ttl>0&&bytes<=65536){while(cache.size>=MERGE_LIMITS.cache_entries||cacheBytes+bytes>MERGE_LIMITS.cache_bytes){const k=cache.keys().next().value;if(k===undefined)break;cacheBytes-=cache.get(k).bytes;cache.delete(k);}cache.set(key,{value:structuredClone(clean),bytes,at,fetchedAt,expires:at+meta.ttl});cacheBytes+=bytes;}return clean;},c.signal).finally(()=>{clearTimeout(timer);if(flights.get(key)===flight)flights.delete(key);});if(method==='GET'||method==='HEAD')flights.set(key,flight);}
flight.subscribers++;return new Promise((resolve,reject)=>{let done=false;const finish=()=>{if(done)return false;done=true;flight.subscribers--;signal?.removeEventListener('abort',abort);return true;};const abort=()=>{if(finish()){const error=new HttpError('cancelled',499);if(!flight.subscribers){flight.cancelled=true;flight.c.abort('All subscribers cancelled');}flight.promise.then(out=>{error.evidence=deliver(out,{started:deliveryStarted,fresh:!coalesced});reject(error);},()=>reject(error));}};signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)return abort();flight.promise.then(out=>{if(finish())resolve({...deliver(out,{started:deliveryStarted,fresh:!coalesced}),cache:{hit:false,coalesced,fetchedAt:out.retrievedAt,source_build:BUILD,ttl_ms:flight.ttl??MERGE_LIMITS.cache_ttl_ms,expiresAt:cache.has(key)?new Date(cache.get(key).expires).toISOString():null,stored:!!cache.get(key),scope:'ephemeral isolate',isolate_id:isolateID()}});},e=>{if(finish())reject(e);});});}
export async function acquireBatch(args,{signal,transport,measure}={}){const batchStarted=Date.now(),c=new AbortController(),abort=()=>c.abort(signal?.reason||'Cancelled');signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)abort();const timer=setTimeout(()=>c.abort('Batch deadline exceeded'),MERGE_LIMITS.batch_ms),items=new Array(args.items.length);let next=0,bytes=0;const base=transport||createGuardedAdapter();const bounded={resolve:base.resolve.bind(base),guardedFetch:async(...a)=>{const r=await base.guardedFetch(...a);if(!r.body)return r;const reader=r.body.getReader();return new Response(new ReadableStream({async pull(controller){try{const x=await reader.read();if(x.done){controller.close();return;}bytes+=x.value.length;if(bytes>MERGE_LIMITS.aggregate_bytes){c.abort('Batch aggregate byte limit');throw new HttpError('batch_byte_limit',413);}controller.enqueue(x.value);}catch(e){controller.error(e);cancelBestEffort(reader);}},cancel:reason=>cancelBestEffort(reader,reason)}),{status:r.status,headers:r.headers});}};try{await Promise.all(Array.from({length:MERGE_LIMITS.active},(_,i)=>i).map(async()=>{for(;;){const index=next++;if(index>=args.items.length)return;const itemStarted=Date.now();try{if(c.signal.aborted)throw new HttpError('cancelled',499);if(bytes>=MERGE_LIMITS.aggregate_bytes)throw new HttpError('batch_byte_limit',413);const out=await mergedRead('acquire',args.items[index],{signal:c.signal,transport:bounded});if(bytes>MERGE_LIMITS.aggregate_bytes)c.abort('Batch aggregate byte limit');items[index]={index,requested_preset:args.items[index].preset||'auto',...out};}catch(e){items[index]={index,...(e.evidence||{}),status:'FAIL',source_status:e.evidence?.status||'FAIL',url:args.items[index].url,error:typed(e),source_complete:e.evidence?.static_provenance?.source_complete??e.evidence?.source_complete??false,duration_ms:Date.now()-itemStarted};}}}));const sum=key=>items.reduce((n,x)=>n+(x.fresh_network?.[key]||0),0);const baseOutput={elapsed_ms:Date.now()-batchStarted,fresh_network:{get_requests:sum('get_requests'),head_requests:sum('head_requests'),dns_requests:sum('dns_requests')},limits:MERGE_LIMITS,aggregate_decoded_bytes:bytes,aggregate_scope:'Decoded destination bodies; DNS receipt bytes excluded',accounting:'Fresh counters count this caller producer only; HIT/coalesced fresh zero. Source work refers to original acquisition.',shared_scope:'per Worker isolate; not global',isolate_id:isolateID(),cache_scope:'ephemeral; durable cache pending',...EGRESS_DISCLOSURE};const output=allocateEvidence(items,baseOutput,{limit:MERGE_LIMITS.output_bytes-(measure?100:2000),measure});output.elapsed_ms=Date.now()-batchStarted;return output;}finally{clearTimeout(timer);signal?.removeEventListener('abort',abort);c.abort('Batch complete');}}
