import {BUILD} from './config.mjs';
import {validateActions,validateSelector,validateTarget} from './actions.mjs';
import {publicURL} from './public-reader.mjs';
export const PLAN_POLICY='sites-browser-structural-plan-v1-get-only';
const obj=x=>x&&typeof x==='object'&&!Array.isArray(x);
const keys=(x,k)=>obj(x)&&Object.keys(x).every(v=>k.includes(v));
export const TARGET_SCHEMA={type:'object',additionalProperties:false,properties:{role:{type:'string',pattern:'^[a-z][a-z-]{0,31}$',maxLength:32},name:{type:'string',maxLength:128},scope:{type:'string',maxLength:256},fingerprint:{type:'string',maxLength:2048}},required:['role','name']};
export const EXTRACTION_SCHEMA={type:'object',additionalProperties:false,properties:{selector:{type:'string',minLength:1,maxLength:256,description:'Bounded simple selector; at most8 components'},target:TARGET_SCHEMA,limit:{type:'integer',minimum:1,maximum:32},fields:{type:'array',minItems:1,maxItems:8,items:{type:'object',additionalProperties:false,properties:{name:{type:'string',pattern:'^[a-zA-Z][\\w-]{0,31}$',maxLength:32},selector:{type:'string',minLength:1,maxLength:256,description:'Bounded simple selector; at most8 components'},attribute:{type:'string',enum:['text','href','title','alt','id','role','type']}},required:['name']}}},required:['fields'],description:'Exactly one selector or semantic target; fields are safe named row projections. Scripts OFF by default.',examples:[{selector:'p',limit:1,fields:[{name:'text',attribute:'text'}]}],if:{required:['selector']},then:{not:{required:['target']}},else:{required:['target']}};
export function validateExtraction(x){if(x===undefined)return;if(!keys(x,['selector','target','limit','fields'])||!!x.selector===!!x.target)throw Error('EXTRACT_POLICY: one selector or semantic target required');if(x.selector)validateSelector(x.selector);else validateTarget(x.target);if(x.limit!==undefined&&(!Number.isInteger(x.limit)||x.limit<1||x.limit>32))throw Error('EXTRACT_POLICY: row limit');if(!Array.isArray(x.fields)||!x.fields.length||x.fields.length>8)throw Error('EXTRACT_POLICY: 1-8 fields');const names=new Set;for(const f of x.fields){if(!keys(f,['name','selector','attribute'])||typeof f.name!=='string'||! /^[a-zA-Z][\w-]{0,31}$/.test(f.name)||names.has(f.name)||f.attribute!==undefined&&!['text','href','title','alt','id','role','type'].includes(f.attribute))throw Error('EXTRACT_POLICY: safe unique fields only');names.add(f.name);if(f.selector!==undefined)validateSelector(f.selector);}return x;}
export function validateOptions(x){if(x.mode==='extract'&&!x.extraction)throw Error('EXTRACT_POLICY: extraction required');if(x.mode==='observe'&&(x.actions?.length||x.plan))throw Error('OBSERVE_POLICY: no mutations or replay');if(x.plan_actions!==undefined&&x.mode!=='observe')throw Error('PLAN_POLICY: templates require observe mode');for(const k of ['execute_scripts','compact'])if(x[k]!==undefined&&typeof x[k]!=='boolean')throw Error('OBSERVE_POLICY: boolean options');if(x.mode!==undefined&&!['execute','observe','extract'].includes(x.mode))throw Error('OBSERVE_POLICY: mode');if(x.scope!==undefined)validateSelector(x.scope);if(x.limits!==undefined){if(!keys(x.limits,['targets','text_chars'])||x.limits.targets!==undefined&&(!Number.isInteger(x.limits.targets)||x.limits.targets<1||x.limits.targets>32)||x.limits.text_chars!==undefined&&(!Number.isInteger(x.limits.text_chars)||x.limits.text_chars<0||x.limits.text_chars>4096))throw Error('OBSERVE_POLICY: bounds');}validateExtraction(x.extraction);if(x.plan_actions!==undefined)validateActions(x.plan_actions,true);if(x.plan!==undefined){const p=x.plan;if(!keys(p,['version','url','build','policy','execute_scripts','document_sha256','script_revision','targets','actions'])||JSON.stringify(p).length>12288||p.version!==1||p.build!==BUILD||p.policy!==PLAN_POLICY||typeof p.execute_scripts!=='boolean'||! /^[a-f0-9]{64}$/.test(p.document_sha256)||! /^[a-f0-9]{64}$/.test(p.script_revision)||!Array.isArray(p.targets)||p.targets.length>32||publicURL(p.url)!==publicURL(x.url))throw Error('PLAN_STALE_OR_INVALID: build/policy/URL/envelope');for(const t of p.targets)validateTarget(t,true);validateActions(p.actions||[],true);if(x.execute_scripts!==undefined&&x.execute_scripts!==p.execute_scripts)throw Error('PLAN_POLICY: execution mode differs');if(x.actions?.length&&p.actions?.length)throw Error('PLAN_POLICY: cannot override planned actions');}if(x.parameters!==undefined){if(!keys(x.parameters,Object.keys(x.parameters))||Object.keys(x.parameters).length>8||JSON.stringify(x.parameters).length>4096||Object.entries(x.parameters).some(([k,v])=>! /^[a-zA-Z][\w-]{0,31}$/.test(k)||/secret|pass|token|credential|auth/i.test(k)||typeof v!=='string'||v.length>1024))throw Error('PLAN_POLICY: bounded nonsecret parameters only');}return x;}
export function materializeActions(options){const a=options.plan?.actions?.length?options.plan.actions:options.actions||[];return validateActions(a.map(x=>{const y={...x};if(y.value_param){if(!Object.hasOwn(options.parameters||{},y.value_param))throw Error('PLAN_POLICY: missing parameter');y.value=options.parameters[y.value_param];delete y.value_param;}return y;}));}
export function compactResult(x){const keep=['status','error','url','original_sha256','initial_script_revision','executed_dom_sha256','observation','plan','plan_reuse','extraction','delta','action_receipts','event_dispatch_count','actions_completed','initial_script_count','executed_source_count','completed_source_count','module_count','dynamic_script_count','js_errors','unsupported_operations','resource_use','teardown','duration_ms','untrusted_source','full_browser','layout','screenshots','connection_pinned','platform_public_only_egress_verified','mode','residual','limits'];const r=Object.fromEntries(keep.filter(k=>x[k]!==undefined).map(k=>[k,x[k]]));r.output_format='compact structural result; omitted full Markdown/network receipts, not token or wire measurements';r.backend_llm_calls=0;return r;}
