import wasmModule from './quickjs.wasm';
import loader from '@jitl/quickjs-wasmfile-release-sync/emscripten-module';
import {QuickJSFFI} from '@jitl/quickjs-wasmfile-release-sync/ffi';
import {newVariant,newQuickJSWASMModuleFromVariant} from 'quickjs-emscripten-core';
import domSource from './dom.txt';
import {LIMITS,allowedURL,boundedRead} from './policy.mjs';
const variant={type:'sync',importFFI:async()=>QuickJSFFI,importModuleLoader:async()=>loader};
let modulePromise,active=0;
export const moduleFor=()=>modulePromise??=(newQuickJSWASMModuleFromVariant(newVariant(variant,{wasmModule})).catch(e=>{modulePromise=undefined;throw e;}));
export function evaluate(vm,code){const r=vm.evalCode(code);if(r.error){let message;try{message=JSON.stringify(vm.dump(r.error));}finally{r.error.dispose();}throw new Error(message);}try{return vm.dump(r.value);}finally{r.value.dispose();}}
export function fixture(nonce){return `<!doctype html><html><head><title>Demo ${nonce}</title></head><body><h1 id="static">STATIC_${nonce}</h1><button id="mutate">Verify public HTTPS</button><output id="result"></output><script>const marker=document.createElement('p');marker.id='dynamic';marker.textContent='SCRIPT_${nonce}';document.body.appendChild(marker);document.querySelector('#mutate').addEventListener('click',async()=>{try{const response=await fetch('https://example.com/');const text=await response.text();const page=DOM.parseHTML(text).document;for(const e of page.querySelectorAll('script,style,noscript,template'))e.remove();if(page.title.trim()!=='Example Domain'||!page.body.textContent.replace(/\\s+/g,' ').includes('This domain is for use in documentation examples without needing permission')||/captcha|access denied|verify.{0,20}human|robot or human/i.test(page.body.textContent))throw new Error('Actual Example Domain content assertion failed');globalThis.__externalProof={title:page.title,meaningful_content:true,paragraphs:page.body.querySelectorAll('p').length,links:page.body.querySelectorAll('a[href]').length,remote_scripts_executed:false};document.querySelector('#result').textContent='CLICK_${nonce}_Example Domain';document.title='Demo_${nonce}_verified';}catch(e){__errors.push(String(e));}});</script></body></html>`;}
export async function sandbox({kind='demo',html,nonce=crypto.randomUUID(),pageURL,signal,scriptOverride}){if(active>=LIMITS.concurrency)return {status:'FAIL',error:'Guest concurrency limit exceeded',teardown:{pending_at_dispose:0,vm_disposed:false}};active++;const started=Date.now(),network=[],deferreds=[],pending=new Set(),controller=new AbortController();let vm,rt,closing=false,timer,requests=0;const teardown={callbacks_started:0,callbacks_settled:0,callbacks_skipped_after_closing:0,pending_at_dispose:null,vm_disposed:false};const abort=()=>controller.abort('Caller cancelled');signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)abort();timer=setTimeout(()=>controller.abort('Host time budget exceeded'),LIMITS.host_ms);let result;
try{const q=await moduleFor();if(controller.signal.aborted)throw new Error('Guest cancelled before initialization');rt=q.newRuntime();rt.setMemoryLimit(LIMITS.guest_bytes);rt.setMaxStackSize(LIMITS.guest_stack);const deadline=Date.now()+LIMITS.guest_ms;rt.setInterruptHandler(()=>controller.signal.aborted||Date.now()>deadline);vm=rt.newContext();const guestFetch=vm.newFunction('__hostFetch',h=>{if(closing||controller.signal.aborted)throw new Error('Guest closing');const dest=allowedURL(vm.getString(h));if(++requests>LIMITS.fetches)throw new Error('Guest fetch count limit exceeded');const deferred=vm.newPromise();deferreds.push(deferred);teardown.callbacks_started++;const task=Promise.resolve().then(async()=>{try{if(closing||controller.signal.aborted)throw new Error('Guest closing');const text=await boundedRead(dest,controller.signal,network);if(closing||controller.signal.aborted){teardown.callbacks_skipped_after_closing++;return;}const value=vm.newString(text);try{deferred.resolve(value);}finally{value.dispose();}}catch(e){if(closing||controller.signal.aborted){teardown.callbacks_skipped_after_closing++;return;}const value=vm.newString(String(e?.message||e).slice(0,512));try{deferred.reject(value);}finally{value.dispose();}}finally{teardown.callbacks_settled++;}});pending.add(task);task.then(()=>pending.delete(task),()=>pending.delete(task));return deferred.handle;});vm.setProp(vm.global,'__hostFetch',guestFetch);guestFetch.dispose();
const decode=vm.newFunction('atob',h=>{const text=vm.getString(h);if(text.length>LIMITS.network_bytes)throw new Error('Base64 decode budget exceeded');return vm.newString(atob(text));});vm.setProp(vm.global,'atob',decode);decode.dispose();evaluate(vm,domSource);
const input=kind==='demo'?fixture(nonce):html;if(typeof input!=='string'||new TextEncoder().encode(input).length>LIMITS.network_bytes)throw new Error('HTML input limit exceeded');evaluate(vm,`globalThis.window=DOM.parseHTML(${JSON.stringify(input)});globalThis.document=window.document;globalThis.Event=DOM.Event;globalThis.__errors=[];globalThis.fetch=async (url,options)=>{if(options!==undefined&&(options===null||typeof options!=='object'||Object.keys(options).some(k=>k!=='method')||(options.method!==undefined&&options.method!=='GET')))throw new Error('Only credential-free GET is supported');const body=await __hostFetch(String(url));return {ok:true,status:200,text:async()=>body,json:async()=>JSON.parse(body)}};`);
if(kind==='demo'){const scripts=JSON.parse(evaluate(vm,"JSON.stringify([...document.querySelectorAll('script')].map(s=>s.textContent))"));for(const code of scripts)evaluate(vm,code);evaluate(vm,scriptOverride??"document.querySelector('#mutate').dispatchEvent(new Event('click'));void 0");for(let step=0;step<LIMITS.microtask_rounds;step++){if(controller.signal.aborted||Date.now()>deadline)throw new Error('Guest interrupted by deadline or cancellation');await Promise.allSettled([...pending]);if(controller.signal.aborted||Date.now()>deadline)throw new Error('Guest interrupted by deadline or cancellation');const jobs=rt.executePendingJobs(LIMITS.jobs_per_round);if(jobs.error){let error;try{error=JSON.stringify(vm.dump(jobs.error));}finally{jobs.error.dispose();}throw new Error(error);}if(!pending.size&&!rt.hasPendingJob())break;if(step===LIMITS.microtask_rounds-1)throw new Error('Microtask budget exhausted');}
const data=JSON.parse(evaluate(vm,"JSON.stringify({title:document.title,static_marker:document.querySelector('#static')?.textContent,script_marker:document.querySelector('#dynamic')?.textContent,click_result:document.querySelector('#result')?.textContent,errors:__errors,external_content_proof:globalThis.__externalProof||null,clean_text:[document.title,document.querySelector('#static')?.textContent,document.querySelector('#dynamic')?.textContent,document.querySelector('#result')?.textContent].filter(Boolean).join('\\n\\n')})"));const verified=data.static_marker==='STATIC_'+nonce&&data.script_marker==='SCRIPT_'+nonce&&data.click_result==='CLICK_'+nonce+'_Example Domain'&&data.title==='Demo_'+nonce+'_verified'&&data.errors.length===0&&network.some(x=>x.url==='https://example.com/'&&x.http_status===200&&x.bytes>0);result={status:verified?'PASS':'FAIL',nonce,fixture_source:'in-process fixed HTML fixture; no Site HTTP request',kind:'sandboxed DOM execution',full_browser:false,layout:false,screenshots:false,...data};
}else{const data=JSON.parse(evaluate(vm,`(()=>{const scriptCount=document.querySelectorAll('script').length;for(const e of document.querySelectorAll('script,style,noscript,template,svg,nav,footer'))e.remove();const text=(document.body?.textContent||'').replace(/\\s+/g,' ').trim().slice(0,${LIMITS.markdown_chars});const title=(document.title||'').replace(/\\s+/g,' ').trim().slice(0,512);const links=[...document.querySelectorAll('a[href]')].slice(0,${LIMITS.links}).map(a=>({text:(a.textContent||'').replace(/\\s+/g,' ').trim().slice(0,120),href:a.getAttribute('href').slice(0,2048)}));return JSON.stringify({title,text,links,script_count:scriptCount});})()`));const links=[];for(const link of data.links){try{const u=new URL(link.href,pageURL);if(u.protocol==='https:'&&!u.username&&!u.password&&!u.port)links.push({text:link.text,url:u.href,untrusted_source:true});}catch{}}
const esc=s=>s.replace(/[\\`*_\[\]<>#]/g,'\\$&');const markdown=('# '+esc(data.title||'Untitled page')+'\n\n'+esc(data.text)+'\n\n'+links.map(l=>'['+esc(l.text||l.url)+']('+l.url.replaceAll('(','%28').replaceAll(')','%29')+')').join('\n')).slice(0,LIMITS.markdown_chars);result={status:'PASS',kind:'static HTML parsing',title:data.title,markdown,links,untrusted_source:true,script_behavior:{executed:false,script_count:data.script_count,unsupported:'Page scripts, external/module scripts, event handlers and script-dependent content are not executed by browser_read_page.'},full_browser:false,layout:false,screenshots:false};}
}catch(e){result={status:'FAIL',error:String(e?.message||e).slice(0,2048),full_browser:false,layout:false,screenshots:false};}
finally{closing=true;controller.abort('Guest teardown');clearTimeout(timer);signal?.removeEventListener('abort',abort);await Promise.allSettled([...pending]);teardown.pending_at_dispose=pending.size;for(const deferred of deferreds)deferred.dispose();vm?.dispose();rt?.dispose();teardown.vm_disposed=!!vm;active--;}
return {...result,resource_use:{get_requests:network.length,head_requests:0,dns_requests:0},network_measurement_basis:'Fixed allowlisted HTTPS transport attempts; no application DNS queries. Platform DNS/TLS internals are not measured.',public_content_normalization_basis:'UTF-8 decoded public response; inert DOM title and whitespace-normalized body; remote scripts/styles/templates excluded before meaningful-content assertion',network,duration_ms:Date.now()-started,teardown};}
export async function readPage(url,signal){const start=Date.now(),network=[];try{const html=await boundedRead(url,signal,network);const output=await sandbox({kind:'read',html,pageURL:url,signal});return {...output,network:[...network,...output.network],duration_ms:Date.now()-start};}catch(e){return {status:'FAIL',error:String(e?.message||e).slice(0,2048),network,duration_ms:Date.now()-start,full_browser:false};}}

export {domSource};
